#!/usr/bin/env bash
#
# add_vehicle.sh - register a new vehicle identity in a signaling server config.
#
# Usage:
#   add_vehicle.sh --id VEHICLE_ID --config YAML_PATH
#                  [--secrets-dir DIR] [--assign-to-driver DRIVER_ID]...
#                  [--force] [--dry-run] [--help]
#
# The script generates a 32-byte hex device token, stores it with mode 0600, adds
#
#   auth:
#     vehicles:
#       - id: <vehicle-id>
#         device_token_file: secrets/<vehicle-id>.token
#
# to the signaling server YAML, and optionally appends the vehicle to the
# `vehicles` permission list of one or more drivers under `auth.drivers`.
#
# Guarantees:
#   * vehicle ids are rejected when they already exist (the server refuses to
#     start on duplicates);
#   * `device_token_file` is written relative to the YAML directory, which is how
#     the server resolves relative secret paths;
#   * the YAML is edited on a sibling temporary copy and only moved into place
#     after `mine-teleop-signaling-server --validate-config` accepts it; a missing
#     validator, missing secret environment variable, or any validation error is
#     fatal;
#   * a token generated by a run that later fails is removed again.
#
# YAML editing backend: `yq` (https://github.com/mikefarah/yq, v4) when present,
# otherwise a python3 + PyYAML fallback that inserts lines in place. Both keep
# surrounding comments and formatting intact.
#
# Environment:
#   MINE_TELEOP_SIGNALING_BIN  explicit path to mine-teleop-signaling-server
#   MINE_TELEOP_BUILD_DIR      build directory searched for the server binary
#   NO_COLOR                   disable colored output
#
set -euo pipefail
umask 077

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(CDPATH= cd -- "$script_dir/../.." && pwd)"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  color_red=$'\033[31m'
  color_green=$'\033[32m'
  color_yellow=$'\033[33m'
  color_blue=$'\033[34m'
  color_bold=$'\033[1m'
  color_reset=$'\033[0m'
else
  color_red="" color_green="" color_yellow="" color_blue="" color_bold="" color_reset=""
fi

step() { printf '%s==>%s %s\n' "$color_blue" "$color_reset" "$*"; }
note() { printf '    %s\n' "$*"; }
ok() { printf '%s ok %s %s\n' "$color_green" "$color_reset" "$*"; }
warn() { printf '%swarn%s %s\n' "$color_yellow" "$color_reset" "$*" >&2; }
fail() { printf '%sfail%s %s\n' "$color_red" "$color_reset" "$*" >&2; exit 2; }

path_mode() {
  stat -c '%a' -- "$1" 2>/dev/null || stat -f '%Lp' -- "$1"
}

path_owner() {
  stat -c '%u' -- "$1" 2>/dev/null || stat -f '%u' -- "$1"
}

normalize_managed_path() {
  local candidate="$1" label="$2" lexical physical
  lexical="$(realpath -ms -- "$candidate")" ||
    fail "cannot normalize $label path: $candidate"
  physical="$(realpath -m -- "$candidate")" ||
    fail "cannot resolve $label path: $candidate"
  [[ "$physical" == "$lexical" ]] ||
    fail "$label path must not contain symbolic links: $candidate"
  printf '%s\n' "$lexical"
}

verify_managed_path() {
  local candidate="$1" label="$2" lexical physical
  lexical="$(realpath -ms -- "$candidate")" ||
    fail "cannot normalize $label path: $candidate"
  physical="$(realpath -m -- "$candidate")" ||
    fail "cannot resolve $label path: $candidate"
  [[ "$physical" == "$lexical" ]] ||
    fail "$label path became symbolic-link based: $candidate"
}

check_owned_directory() {
  local directory="$1" label="$2" mode owner
  [[ ! -L "$directory" ]] || fail "$label must not be a symbolic link: $directory"
  [[ -d "$directory" ]] || fail "$label is not a directory: $directory"
  owner="$(path_owner "$directory")" || fail "cannot read owner of $label: $directory"
  [[ "$owner" == "$EUID" ]] ||
    fail "$label must be owned by uid $EUID (found uid $owner): $directory"
  mode="$(path_mode "$directory")" || fail "cannot read mode of $label: $directory"
  [[ "$mode" =~ ^[0-7]{3,4}$ ]] || fail "cannot parse mode '$mode' for $label: $directory"
  (( (8#$mode & 0022) == 0 )) ||
    fail "$label must not be group- or world-writable (mode $mode): $directory"
  [[ -w "$directory" ]] || fail "$label is not writable: $directory"
}

harden_private_directory() {
  local directory="$1" label="$2"
  verify_managed_path "$directory" "$label"
  check_owned_directory "$directory" "$label"
  chmod 0700 "$directory"
  [[ "$(path_mode "$directory")" == '700' ]] ||
    fail "$label could not be restricted to mode 0700: $directory"
}

usage() {
  cat <<'EOF'
Usage:
  add_vehicle.sh --id VEHICLE_ID --config YAML_PATH [options]

Required:
  --id VEHICLE_ID              vehicle identity to register, e.g. vehicle-003
  --config YAML_PATH           signaling server multi-identity YAML

Options:
  --secrets-dir DIR            token directory (default: <yaml dir>/secrets)
  --backup-dir DIR             config backup directory (default: <yaml dir>/backups)
  --assign-to-driver DRIVER_ID append the vehicle to this driver's permission
                               list; may be repeated
  --force                      overwrite an existing token file
  --dry-run                    render and report the plan without changing YAML,
                               credentials, or backups
  --help                       show this help

Examples:
  add_vehicle.sh --id vehicle-003 --config /etc/mine-teleop/signaling-server.yaml
  add_vehicle.sh --id vehicle-003 --config configs/signaling-server.2x2.dev.yaml \
      --assign-to-driver driver-console-001 --dry-run
EOF
}

# ---------------------------------------------------------------------------
# YAML backend
# ---------------------------------------------------------------------------

yaml_engine=""

select_yaml_engine() {
  if command -v yq >/dev/null 2>&1 && yq --version 2>/dev/null | grep -qi 'mikefarah\|version v4'; then
    yaml_engine="yq"
    return 0
  fi
  if command -v python3 >/dev/null 2>&1 && python3 -c 'import yaml' >/dev/null 2>&1; then
    yaml_engine="python"
    if command -v yq >/dev/null 2>&1; then
      warn "the yq on PATH is not mikefarah/yq v4; using the python3 fallback editor"
    else
      warn "yq (https://github.com/mikefarah/yq) not found; using the python3 fallback editor"
    fi
    return 0
  fi
  fail "no YAML backend available: install mikefarah/yq v4, or python3 with PyYAML"
}

# Embedded fallback editor. Reads/edits the YAML as text so comments, key order
# and indentation survive; PyYAML is only used for the read-only queries.
python_yaml() {
  python3 - "$@" <<'PYTHON'
import json
import re
import sys

mode, path = sys.argv[1], sys.argv[2]
arguments = sys.argv[3:]


def die(message):
    sys.stderr.write("yaml edit failed: %s\n" % message)
    raise SystemExit(2)


def load_text():
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    trailing_newline = text.endswith("\n")
    lines = text.split("\n")
    if trailing_newline:
        lines.pop()
    return lines, trailing_newline


def store_text(lines, trailing_newline):
    text = "\n".join(lines)
    if trailing_newline:
        text += "\n"
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def indent_of(line):
    return len(line) - len(line.lstrip(" "))


def is_filler(line):
    stripped = line.strip()
    return stripped == "" or stripped.startswith("#")


def block_end(lines, key_index, limit=None):
    """Index just past the last content line owned by the key at key_index."""
    base = indent_of(lines[key_index])
    limit = len(lines) if limit is None else limit
    end = key_index + 1
    index = key_index + 1
    while index < limit:
        line = lines[index]
        if is_filler(line):
            index += 1
            continue
        current = indent_of(line)
        if current > base or (current == base and line.lstrip().startswith("- ")):
            end = index + 1
            index += 1
            continue
        break
    return end


def find_key(lines, start, limit, key, indent=None):
    escaped = re.escape(key)
    pattern = re.compile(
        r"^( *)(?:%s|\"%s\"|'%s'):( *)(.*)$" %
        (escaped, escaped, escaped))
    matches = []
    for index in range(start, limit):
        match = pattern.match(lines[index])
        if match is None:
            continue
        if indent is not None and len(match.group(1)) != indent:
            continue
        matches.append((index, match.group(3).strip()))
    if len(matches) > 1:
        die("`%s` appears more than once at the same mapping level" % key)
    if matches:
        return matches[0]
    return -1, ""


def child_indent(lines, key_index, limit, default):
    for index in range(key_index + 1, limit):
        if is_filler(lines[index]):
            continue
        return indent_of(lines[index])
    return default


def sequence_indent(lines, start, limit, default):
    for index in range(start, limit):
        line = lines[index]
        if is_filler(line):
            continue
        if line.lstrip().startswith("- "):
            return indent_of(line)
    return default


def auth_section(lines, section):
    auth_index, auth_inline = find_key(lines, 0, len(lines), "auth", indent=0)
    if auth_index < 0:
        die("top level `auth` mapping not found")
    if auth_inline:
        die("`auth` must be a block mapping, found an inline value")
    auth_limit = block_end(lines, auth_index)
    auth_child = child_indent(lines, auth_index, auth_limit, 2)
    section_index, section_inline = find_key(
        lines, auth_index + 1, auth_limit, section, indent=auth_child)
    return auth_index, auth_limit, auth_child, section_index, section_inline


def quote(value):
    # Match yq's strenv semantics even for YAML-reserved scalars such as
    # `true`, `null`, timestamps and numeric-looking identity values.
    return json.dumps(value, ensure_ascii=False)


def parsed_document():
    try:
        import yaml
    except ImportError:
        die("PyYAML is required for the python fallback backend")
    with open(path, "r", encoding="utf-8") as handle:
        document = yaml.safe_load(handle)
    if document is None:
        document = {}
    if not isinstance(document, dict):
        die("config root must be a mapping")
    return document


def entries(section):
    document = parsed_document()
    auth = document.get("auth") or {}
    if not isinstance(auth, dict):
        die("`auth` must be a mapping")
    items = auth.get(section) or []
    if not isinstance(items, list):
        die("`auth.%s` must be a sequence" % section)
    return items


if mode == "ids":
    for entry in entries(arguments[0]):
        if isinstance(entry, dict) and entry.get("id") is not None:
            print(entry["id"])
    raise SystemExit(0)

if mode == "driver-vehicles":
    driver_id = arguments[0]
    for entry in entries("drivers"):
        if not isinstance(entry, dict) or entry.get("id") != driver_id:
            continue
        for vehicle in entry.get("vehicles") or []:
            print(vehicle)
    raise SystemExit(0)

if mode == "add-vehicle":
    vehicle_id, token_path = arguments[0], arguments[1]
    lines, trailing_newline = load_text()
    auth_index, auth_limit, auth_child, index, inline = auth_section(lines, "vehicles")

    if index < 0:
        item = auth_child + 2
        insert_at = block_end(lines, auth_index)
        payload = [
            " " * auth_child + "vehicles:",
            " " * item + "- id: " + quote(vehicle_id),
            " " * (item + 2) + "device_token_file: " + quote(token_path),
        ]
    else:
        if inline and inline != "[]":
            die("`auth.vehicles` uses an inline sequence; install mikefarah/yq v4 to edit it")
        if inline == "[]":
            lines[index] = " " * auth_child + "vehicles:"
            item = auth_child + 2
            insert_at = index + 1
        else:
            limit = block_end(lines, index, auth_limit)
            item = sequence_indent(lines, index + 1, limit, auth_child + 2)
            insert_at = limit
        payload = [
            " " * item + "- id: " + quote(vehicle_id),
            " " * (item + 2) + "device_token_file: " + quote(token_path),
        ]

    lines[insert_at:insert_at] = payload
    store_text(lines, trailing_newline)
    raise SystemExit(0)

if mode == "assign":
    driver_id, vehicle_id = arguments[0], arguments[1]
    lines, trailing_newline = load_text()
    _, _, auth_child, drivers_index, drivers_inline = auth_section(lines, "drivers")
    if drivers_index < 0:
        die("`auth.drivers` not found, cannot assign the vehicle")
    if drivers_inline:
        die("`auth.drivers` uses an inline sequence; install mikefarah/yq v4 to edit it")

    drivers_limit = block_end(lines, drivers_index, None)
    item = sequence_indent(lines, drivers_index + 1, drivers_limit, auth_child + 2)

    starts = [index for index in range(drivers_index + 1, drivers_limit)
              if indent_of(lines[index]) == item and lines[index].lstrip().startswith("- ")]
    span = None
    for position, start in enumerate(starts):
        stop = starts[position + 1] if position + 1 < len(starts) else drivers_limit
        head = re.match(r"^ *- +(?:id|\"id\"|'id'): *(.*)$", lines[start])
        matched = head is not None and head.group(1).strip().strip("\"'") == driver_id
        if not matched:
            body, value = find_key(lines, start + 1, stop, "id", indent=item + 2)
            if body >= 0:
                matched = value.strip("\"'") == driver_id
        if matched:
            span = (start, stop)
            break
    if span is None:
        die("driver `%s` not found under auth.drivers" % driver_id)

    start, stop = span
    key_index, inline = find_key(lines, start, stop, "vehicles", indent=item + 2)
    if key_index < 0:
        insert_at = block_end(lines, start, stop)
        payload = [
            " " * (item + 2) + "vehicles:",
            " " * (item + 4) + "- " + quote(vehicle_id),
        ]
    elif inline:
        if not (inline.startswith("[") and inline.endswith("]")):
            die("driver `%s` has an unsupported `vehicles` value" % driver_id)
        existing = inline[1:-1].strip()
        merged = "[%s]" % (quote(vehicle_id) if not existing
                           else "%s, %s" % (existing, quote(vehicle_id)))
        lines[key_index] = " " * (item + 2) + "vehicles: " + merged
        store_text(lines, trailing_newline)
        raise SystemExit(0)
    else:
        limit = block_end(lines, key_index, stop)
        entry_indent = sequence_indent(lines, key_index + 1, limit, item + 4)
        insert_at = limit
        payload = [" " * entry_indent + "- " + quote(vehicle_id)]

    lines[insert_at:insert_at] = payload
    store_text(lines, trailing_newline)
    raise SystemExit(0)

die("unknown mode: %s" % mode)
PYTHON
}

yaml_ids() {
  local file="$1" section="$2"
  case "$yaml_engine" in
    yq)
      # Literal paths rather than a dynamic key: `.auth[strenv(...)]` support
      # varies across yq v4 releases.
      if [[ "$section" == "vehicles" ]]; then
        yq eval '(.auth.vehicles // [])[].id // ""' -- "$file"
      else
        yq eval '(.auth.drivers // [])[].id // ""' -- "$file"
      fi
      ;;
    python) python_yaml ids "$file" "$section" ;;
  esac
}

yaml_driver_vehicles() {
  local file="$1" driver="$2"
  case "$yaml_engine" in
    yq)
      DRIVER="$driver" yq eval \
        '(.auth.drivers // [])[] | select(.id == strenv(DRIVER)) | (.vehicles // [])[]' -- "$file"
      ;;
    python) python_yaml driver-vehicles "$file" "$driver" ;;
  esac
}

yaml_add_vehicle() {
  local file="$1" vehicle="$2" token="$3"
  case "$yaml_engine" in
    yq)
      VEHICLE="$vehicle" TOKEN="$token" yq eval -i \
        '.auth.vehicles += [{"id": strenv(VEHICLE), "device_token_file": strenv(TOKEN)}]' -- "$file"
      ;;
    python) python_yaml add-vehicle "$file" "$vehicle" "$token" ;;
  esac
}

yaml_assign_vehicle() {
  local file="$1" driver="$2" vehicle="$3"
  case "$yaml_engine" in
    yq)
      DRIVER="$driver" VEHICLE="$vehicle" yq eval -i \
        '(.auth.drivers[] | select(.id == strenv(DRIVER)) | .vehicles) += [strenv(VEHICLE)]' -- "$file"
      ;;
    python) python_yaml assign "$file" "$driver" "$vehicle" ;;
  esac
}

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

vehicle_id=""
config_path=""
secrets_dir=""
backup_dir=""
dry_run="no"
force="no"
drivers=()

while (($#)); do
  case "$1" in
    --id)
      [[ $# -ge 2 ]] || fail "--id requires a value"
      vehicle_id="$2"
      shift 2
      ;;
    --config)
      [[ $# -ge 2 ]] || fail "--config requires a value"
      config_path="$2"
      shift 2
      ;;
    --secrets-dir)
      [[ $# -ge 2 ]] || fail "--secrets-dir requires a value"
      secrets_dir="$2"
      shift 2
      ;;
    --backup-dir)
      [[ $# -ge 2 && -n "$2" ]] || fail "--backup-dir requires a value"
      backup_dir="$2"
      shift 2
      ;;
    --assign-to-driver)
      [[ $# -ge 2 ]] || fail "--assign-to-driver requires a value"
      drivers+=("$2")
      shift 2
      ;;
    --force)
      force="yes"
      shift
      ;;
    --dry-run)
      dry_run="yes"
      shift
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *)
      printf 'unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ -n "$vehicle_id" ]] || { printf 'missing --id\n' >&2; usage >&2; exit 2; }
[[ -n "$config_path" ]] || { printf 'missing --config\n' >&2; usage >&2; exit 2; }
[[ "$vehicle_id" =~ ^[A-Za-z0-9._-]+$ ]] ||
  fail "vehicle id may only contain letters, digits, dot, underscore and dash: $vehicle_id"
[[ ! -L "$config_path" ]] || fail "config file must not be a symbolic link: $config_path"
[[ -f "$config_path" && -r "$config_path" ]] || fail "config is not a readable file: $config_path"
[[ -w "$config_path" ]] || fail "config is not writable: $config_path"

for driver in ${drivers[@]+"${drivers[@]}"}; do
  [[ "$driver" =~ ^[A-Za-z0-9._-]+$ ]] ||
    fail "driver id may only contain letters, digits, dot, underscore and dash: $driver"
done

# De-duplicate repeated --assign-to-driver values while keeping the given order.
unique_drivers=()
for driver in ${drivers[@]+"${drivers[@]}"}; do
  known="no"
  for seen in ${unique_drivers[@]+"${unique_drivers[@]}"}; do
    if [[ "$seen" == "$driver" ]]; then known="yes"; break; fi
  done
  [[ "$known" == "yes" ]] || unique_drivers+=("$driver")
done
drivers=(${unique_drivers[@]+"${unique_drivers[@]}"})

command -v openssl >/dev/null 2>&1 || fail "openssl is required to generate the device token"
command -v flock >/dev/null 2>&1 || fail "flock is required to serialize config updates"
select_yaml_engine

config_path="$(CDPATH= cd -- "$(dirname -- "$config_path")" && pwd -P)/$(basename -- "$config_path")"
config_dir="$(dirname -- "$config_path")"
[[ ! -L "$config_path" ]] || fail "config file must not be a symbolic link: $config_path"
check_owned_directory "$config_dir" "config directory"
# The default credential directory is resolved against the config directory so
# the recorded device_token_file stays relative to the YAML. An explicit
# --secrets-dir is resolved against the caller's CWD (matching add_driver.sh).
if [[ -z "$secrets_dir" ]]; then
  secrets_dir="$config_dir/secrets"
elif [[ "$secrets_dir" != /* ]]; then
  secrets_dir="$PWD/$secrets_dir"
fi
secrets_dir="${secrets_dir%/}"
if [[ -z "$backup_dir" ]]; then
  backup_dir="$config_dir/backups"
elif [[ "$backup_dir" != /* ]]; then
  backup_dir="$PWD/$backup_dir"
fi
backup_dir="${backup_dir%/}"

secrets_dir="$(normalize_managed_path "$secrets_dir" "secrets directory")"
backup_dir="$(normalize_managed_path "$backup_dir" "backup directory")"
token_path="$secrets_dir/${vehicle_id}.token"

[[ ! -L "$secrets_dir" ]] || fail "secrets directory must not be a symbolic link: $secrets_dir"
[[ ! -L "$backup_dir" ]] || fail "backup directory must not be a symbolic link: $backup_dir"
if [[ -e "$secrets_dir" ]]; then
  check_owned_directory "$secrets_dir" "secrets directory"
fi
if [[ -e "$backup_dir" ]]; then
  check_owned_directory "$backup_dir" "backup directory"
fi

# Share one lock with add_driver.sh so all identity changes are serialized.
lock_path="${config_path}.admin.lock"
[[ ! -L "$lock_path" ]] || fail "config lock must not be a symbolic link: $lock_path"
exec 9>>"$lock_path"
flock -x 9
[[ ! -L "$config_path" ]] || fail "config file became a symbolic link while acquiring the lock: $config_path"

# `device_token_file` is resolved relative to the config directory by the server,
# so prefer a relative reference. The plain prefix strip keeps the common case
# working without GNU realpath (BSD/macOS lacks --relative-to).
case "$token_path" in
  "$config_dir"/*)
    token_reference="${token_path#"$config_dir"/}"
    ;;
  *)
    token_reference="$(realpath --relative-to="$config_dir" -m -- "$token_path" 2>/dev/null || true)"
    if [[ -z "$token_reference" || "$token_reference" == ..* ]]; then
      token_reference="$(realpath -m -- "$token_path" 2>/dev/null || printf '%s' "$token_path")"
    fi
    ;;
esac

# ---------------------------------------------------------------------------
# Validation against the current config
# ---------------------------------------------------------------------------

step "inspecting $config_path"
# Read in the parent shell: a backend failure must abort here, because an
# unreadable section would otherwise look like an empty one and defeat the
# duplicate checks below.
vehicles_raw="$(yaml_ids "$config_path" vehicles)" ||
  fail "cannot read auth.vehicles from $config_path (is it valid YAML?)"
drivers_raw="$(yaml_ids "$config_path" drivers)" ||
  fail "cannot read auth.drivers from $config_path (is it valid YAML?)"

existing_vehicles=()
while IFS= read -r line; do
  if [[ -n "$line" ]]; then existing_vehicles+=("$line"); fi
done <<<"$vehicles_raw"
existing_drivers=()
while IFS= read -r line; do
  if [[ -n "$line" ]]; then existing_drivers+=("$line"); fi
done <<<"$drivers_raw"

for existing in ${existing_vehicles[@]+"${existing_vehicles[@]}"}; do
  if [[ "$existing" == "$vehicle_id" ]]; then
    fail "vehicle id already present in $config_path: $vehicle_id (the server rejects duplicates)"
  fi
done
note "vehicles configured: ${#existing_vehicles[@]}, drivers configured: ${#existing_drivers[@]}"

assign_drivers=()
for driver in ${drivers[@]+"${drivers[@]}"}; do
  known="no"
  for existing in ${existing_drivers[@]+"${existing_drivers[@]}"}; do
    if [[ "$existing" == "$driver" ]]; then known="yes"; break; fi
  done
  [[ "$known" == "yes" ]] || fail "driver not found in $config_path: $driver"
  permitted_raw="$(yaml_driver_vehicles "$config_path" "$driver")" ||
    fail "cannot read the vehicle permissions of $driver from $config_path"
  already="no"
  while IFS= read -r permitted; do
    if [[ "$permitted" == "$vehicle_id" ]]; then already="yes"; fi
  done <<<"$permitted_raw"
  if [[ "$already" == "yes" ]]; then
    warn "$driver already lists $vehicle_id; leaving its permissions untouched"
  else
    assign_drivers+=("$driver")
  fi
done

[[ ! -L "$token_path" ]] || fail "token file must not be a symbolic link: $token_path"
if [[ -e "$token_path" && "$force" != "yes" ]]; then
  fail "token file already exists: $token_path (pass --force to regenerate it)"
fi
if [[ -e "$token_path" && ! -f "$token_path" ]]; then
  fail "token path is not a regular file: $token_path"
fi

# ---------------------------------------------------------------------------
# Config validator discovery
# ---------------------------------------------------------------------------

find_validator() {
  local candidate
  if [[ -n "${MINE_TELEOP_SIGNALING_BIN:-}" ]]; then
    printf '%s' "$MINE_TELEOP_SIGNALING_BIN"
    return 0
  fi
  if candidate="$(command -v mine-teleop-signaling-server 2>/dev/null)"; then
    printf '%s' "$candidate"
    return 0
  fi
  if [[ -x "$script_dir/bin/mine-teleop-signaling-server" ]]; then
    printf '%s' "$script_dir/bin/mine-teleop-signaling-server"
    return 0
  fi
  for candidate in \
    "${MINE_TELEOP_BUILD_DIR:-$repo_root/build}/mine-teleop-signaling-server" \
    "$repo_root"/build/*/mine-teleop-signaling-server; do
    [[ -x "$candidate" ]] || continue
    printf '%s' "$candidate"
    return 0
  done
  return 1
}

# Validate a rendered config. Every non-zero validator result is fatal; callers
# must export any environment-backed identity secrets required by the config.
validation_note=""
validate_config() {
  local file="$1" output status=0
  output="$("${validator_command[@]}" --validate-config --config "$file" 2>&1)" || status=$?
  if [[ $status -eq 0 ]]; then
    validation_note="passed"
    return 0
  fi
  printf '%s\n' "$output" >&2
  return "$status"
}

validator=""
validator_command=()
# Checked here rather than inside find_validator: that runs in a command
# substitution, where an abort would only end the subshell.
if [[ -n "${MINE_TELEOP_SIGNALING_BIN:-}" && ! -x "${MINE_TELEOP_SIGNALING_BIN}" ]]; then
  fail "MINE_TELEOP_SIGNALING_BIN is not executable: $MINE_TELEOP_SIGNALING_BIN"
fi
if validator="$(find_validator)"; then
  validator_command=("$validator")
  validator_prefix="$(CDPATH= cd -- "$(dirname -- "$validator")/.." && pwd)"
  bundled_loader="$validator_prefix/lib/ld-linux-x86-64.so.2"
  if [[ -x "$bundled_loader" && -d "$validator_prefix/lib" ]]; then
    validator_command=(
      "$bundled_loader"
      --library-path "$validator_prefix/lib"
      "$validator")
  fi
  note "validator: $validator"
else
  fail "mine-teleop-signaling-server validator is required; set MINE_TELEOP_SIGNALING_BIN"
fi

# ---------------------------------------------------------------------------
# Candidate rendering shared by dry-run and apply
# ---------------------------------------------------------------------------

created_token="no"
created_secrets_dir="no"
temporary_config=""
committed="no"
token_staging=""
token_rollback=""
token_existed_before="no"
backup_path=""

cleanup() {
  [[ -z "$temporary_config" ]] || rm -f -- "$temporary_config"
  [[ -z "$token_staging" ]] || rm -f -- "$token_staging"
  if [[ "$committed" != "yes" && "$created_token" == "yes" ]]; then
    if [[ "$token_existed_before" == "yes" && -n "$token_rollback" ]]; then
      mv -f -- "$token_rollback" "$token_path"
      token_rollback=""
      warn "restored the previous token because the config was not updated"
    else
      rm -f -- "$token_path"
      warn "removed the freshly generated token $token_path because the config was not updated"
    fi
  fi
  [[ -z "$token_rollback" ]] || rm -f -- "$token_rollback"
  if [[ "$committed" != "yes" && "$created_secrets_dir" == "yes" ]]; then
    rmdir -- "$secrets_dir" 2>/dev/null || true
  fi
  return 0
}
trap cleanup EXIT

render_candidate() {
  local target="$1" driver
  cat -- "$config_path" >"$target"
  yaml_add_vehicle "$target" "$vehicle_id" "$token_reference"
  for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
    yaml_assign_vehicle "$target" "$driver" "$vehicle_id"
  done

  if [[ "$(yaml_ids "$target" vehicles | grep -c -x -F -- "$vehicle_id")" != "1" ]]; then
    fail "the rendered config does not contain exactly one '$vehicle_id' vehicle; $config_path is unchanged"
  fi
  for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
    if ! yaml_driver_vehicles "$target" "$driver" | grep -q -x -F -- "$vehicle_id"; then
      fail "driver $driver did not gain $vehicle_id in the rendered config; $config_path is unchanged"
    fi
  done
}

temporary_config="$(mktemp "$config_dir/.add_vehicle.$(basename -- "$config_path").XXXXXX")"
render_candidate "$temporary_config"

# ---------------------------------------------------------------------------
# Dry run
# ---------------------------------------------------------------------------

if [[ "$dry_run" == "yes" ]]; then
  step "dry run: YAML, credentials, and backups are unchanged"
  note "token file            $token_path (mode 0600, 32 random bytes hex)"
  note "secrets directory     $secrets_dir$([[ -d "$secrets_dir" ]] || printf ' (would be created, mode 0700)')"
  note "yaml                  $config_path"
  note "backend               $yaml_engine"
  note "config backup         $backup_dir"
  if command -v diff >/dev/null 2>&1; then
    diff -u --label "$(basename -- "$config_path")" \
      --label "$(basename -- "$config_path") (after)" \
      -- "$config_path" "$temporary_config" || true
  fi
  note "would validate with ${validator_command[*]} --validate-config"
  ok "dry run finished; rerun without --dry-run to apply"
  exit 0
fi

# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

step "generating device token"
if [[ ! -d "$secrets_dir" ]]; then
  verify_managed_path "$secrets_dir" "secrets directory"
  mkdir -- "$secrets_dir"
  created_secrets_dir="yes"
  note "created $secrets_dir (mode 0700)"
fi
harden_private_directory "$secrets_dir" "secrets directory"

token_staging="$(mktemp "$secrets_dir/.${vehicle_id}.token.XXXXXX")"
if ! openssl rand -hex 32 >"$token_staging"; then
  fail "openssl failed to generate a device token for $vehicle_id"
fi
chmod 0600 "$token_staging"
if [[ -e "$token_path" ]]; then
  token_existed_before="yes"
  token_rollback="$(mktemp "$secrets_dir/.${vehicle_id}.token.rollback.XXXXXX")"
  cp -p -- "$token_path" "$token_rollback"
  mv -f -- "$token_staging" "$token_path"
  created_token="yes"
else
  if ! ln -- "$token_staging" "$token_path"; then
    fail "token target appeared while provisioning; refusing to overwrite it: $token_path"
  fi
  created_token="yes"
  rm -f -- "$token_staging"
fi
token_staging=""
chmod 0600 "$token_path"
[[ -n "$(tr -d '[:space:]' <"$token_path")" ]] || fail "generated token file is empty: $token_path"
ok "wrote $token_path (mode 0600)"

note "auth.vehicles += $vehicle_id"
for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
  note "auth.drivers[$driver].vehicles += $vehicle_id"
done

step "validating the updated config"
if ! validate_config "$temporary_config"; then
  fail "the updated config was rejected; $config_path is unchanged"
fi
ok "mine-teleop-signaling-server --validate-config accepted the config"

# Back up only after the pending config passed validation.
if [[ ! -d "$backup_dir" ]]; then
  verify_managed_path "$backup_dir" "backup directory"
  mkdir -- "$backup_dir"
fi
harden_private_directory "$backup_dir" "backup directory"
backup_path="$backup_dir/$(basename -- "$config_path").$(date -u +%Y%m%d-%H%M%S)-$$.bak"
cp -p -- "$config_path" "$backup_path"

config_mode="$(stat -c '%a' -- "$config_path" 2>/dev/null || stat -f '%Lp' -- "$config_path")"
chmod "$config_mode" "$temporary_config"
if [[ "$EUID" -eq 0 ]]; then
  config_owner="$(stat -c '%u:%g' -- "$config_path" 2>/dev/null || stat -f '%u:%g' -- "$config_path")"
  chown "$config_owner" -- "$temporary_config"
fi
mv -f -- "$temporary_config" "$config_path"
temporary_config=""
committed="yes"
ok "updated $config_path"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

printf '\n%ssummary%s\n' "$color_bold" "$color_reset"
printf '  vehicle id       %s\n' "$vehicle_id"
printf '  token file       %s\n' "$token_path"
printf '  token reference  device_token_file: %s\n' "$token_reference"
printf '  config           %s\n' "$config_path"
printf '  backup           %s\n' "$backup_path"
if ((${#assign_drivers[@]})); then
  printf '  drivers updated  %s\n' "${assign_drivers[*]}"
else
  printf '  drivers updated  none (no driver may reach %s yet)\n' "$vehicle_id"
fi
printf '  validation       passed\n'
printf '  activation       next matching vehicle connection; cloud restart not required\n'
printf 'Then provision %s on the vehicle: copy the token to its host and point\n' "$vehicle_id"
printf 'cloud.device_token_file at it in the vehicle agent config.\n'
