#!/usr/bin/env bash
#
# add_vehicle.sh - register a new vehicle identity in a signaling server config.
#
# Usage:
#   add_vehicle.sh --id VEHICLE_ID --config YAML_PATH
#                  [--secrets-dir DIR] [--assign-to-driver DRIVER_ID]...
#                  [--force] [--dry-run] [--help]
#
# The script generates a 32-byte hex device token, stores it with mode 0600, adds
#
#   auth:
#     vehicles:
#       - id: <vehicle-id>
#         device_token_file: secrets/<vehicle-id>.token
#
# to the signaling server YAML, and optionally appends the vehicle to the
# `vehicles` permission list of one or more drivers under `auth.drivers`.
#
# Guarantees:
#   * vehicle ids are rejected when they already exist (the server refuses to
#     start on duplicates);
#   * `device_token_file` is written relative to the YAML directory, which is how
#     the server resolves relative secret paths;
#   * the YAML is edited on a sibling temporary copy and only moved into place
#     after `mine-teleop-signaling-server --validate-config` accepts it (skipped
#     when the binary is unavailable, or when the untouched config already fails
#     validation in this environment, e.g. because `password_env` secrets are not
#     exported);
#   * a token generated by a run that later fails is removed again.
#
# YAML editing backend: `yq` (https://github.com/mikefarah/yq, v4) when present,
# otherwise a python3 + PyYAML fallback that inserts lines in place. Both keep
# surrounding comments and formatting intact.
#
# Environment:
#   MINE_TELEOP_SIGNALING_BIN  explicit path to mine-teleop-signaling-server
#   MINE_TELEOP_BUILD_DIR      build directory searched for the server binary
#   NO_COLOR                   disable colored output
#
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(CDPATH= cd -- "$script_dir/../.." && pwd)"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  color_red=$'\033[31m'
  color_green=$'\033[32m'
  color_yellow=$'\033[33m'
  color_blue=$'\033[34m'
  color_bold=$'\033[1m'
  color_reset=$'\033[0m'
else
  color_red="" color_green="" color_yellow="" color_blue="" color_bold="" color_reset=""
fi

step() { printf '%s==>%s %s\n' "$color_blue" "$color_reset" "$*"; }
note() { printf '    %s\n' "$*"; }
ok() { printf '%s ok %s %s\n' "$color_green" "$color_reset" "$*"; }
warn() { printf '%swarn%s %s\n' "$color_yellow" "$color_reset" "$*" >&2; }
fail() { printf '%sfail%s %s\n' "$color_red" "$color_reset" "$*" >&2; exit 2; }

usage() {
  cat <<'EOF'
Usage:
  add_vehicle.sh --id VEHICLE_ID --config YAML_PATH [options]

Required:
  --id VEHICLE_ID              vehicle identity to register, e.g. vehicle-003
  --config YAML_PATH           signaling server multi-identity YAML

Options:
  --secrets-dir DIR            token directory (default: <yaml dir>/secrets)
  --assign-to-driver DRIVER_ID append the vehicle to this driver's permission
                               list; may be repeated
  --force                      overwrite an existing token file
  --dry-run                    report the planned changes without writing
  --help                       show this help

Examples:
  add_vehicle.sh --id vehicle-003 --config /etc/mine-teleop/signaling-server.yaml
  add_vehicle.sh --id vehicle-003 --config configs/signaling-server.2x2.dev.yaml \
      --assign-to-driver driver-console-001 --dry-run
EOF
}

# ---------------------------------------------------------------------------
# YAML backend
# ---------------------------------------------------------------------------

yaml_engine=""

select_yaml_engine() {
  if command -v yq >/dev/null 2>&1 && yq --version 2>/dev/null | grep -qi 'mikefarah\|version v4'; then
    yaml_engine="yq"
    return 0
  fi
  if command -v python3 >/dev/null 2>&1 && python3 -c 'import yaml' >/dev/null 2>&1; then
    yaml_engine="python"
    if command -v yq >/dev/null 2>&1; then
      warn "the yq on PATH is not mikefarah/yq v4; using the python3 fallback editor"
    else
      warn "yq (https://github.com/mikefarah/yq) not found; using the python3 fallback editor"
    fi
    return 0
  fi
  fail "no YAML backend available: install mikefarah/yq v4, or python3 with PyYAML"
}

# Embedded fallback editor. Reads/edits the YAML as text so comments, key order
# and indentation survive; PyYAML is only used for the read-only queries.
python_yaml() {
  python3 - "$@" <<'PYTHON'
import re
import sys

mode, path = sys.argv[1], sys.argv[2]
arguments = sys.argv[3:]


def die(message):
    sys.stderr.write("yaml edit failed: %s\n" % message)
    raise SystemExit(2)


def load_text():
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    trailing_newline = text.endswith("\n")
    lines = text.split("\n")
    if trailing_newline:
        lines.pop()
    return lines, trailing_newline


def store_text(lines, trailing_newline):
    text = "\n".join(lines)
    if trailing_newline:
        text += "\n"
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)


def indent_of(line):
    return len(line) - len(line.lstrip(" "))


def is_filler(line):
    stripped = line.strip()
    return stripped == "" or stripped.startswith("#")


def block_end(lines, key_index, limit=None):
    """Index just past the last content line owned by the key at key_index."""
    base = indent_of(lines[key_index])
    limit = len(lines) if limit is None else limit
    end = key_index + 1
    index = key_index + 1
    while index < limit:
        line = lines[index]
        if is_filler(line):
            index += 1
            continue
        current = indent_of(line)
        if current > base or (current == base and line.lstrip().startswith("- ")):
            end = index + 1
            index += 1
            continue
        break
    return end


def find_key(lines, start, limit, key, indent=None):
    pattern = re.compile(r"^( *)" + re.escape(key) + r":( *)(.*)$")
    for index in range(start, limit):
        match = pattern.match(lines[index])
        if match is None:
            continue
        if indent is not None and len(match.group(1)) != indent:
            continue
        return index, match.group(3).strip()
    return -1, ""


def child_indent(lines, key_index, limit, default):
    for index in range(key_index + 1, limit):
        if is_filler(lines[index]):
            continue
        return indent_of(lines[index])
    return default


def sequence_indent(lines, start, limit, default):
    for index in range(start, limit):
        line = lines[index]
        if is_filler(line):
            continue
        if line.lstrip().startswith("- "):
            return indent_of(line)
    return default


def auth_section(lines, section):
    auth_index, auth_inline = find_key(lines, 0, len(lines), "auth", indent=0)
    if auth_index < 0:
        die("top level `auth` mapping not found")
    if auth_inline:
        die("`auth` must be a block mapping, found an inline value")
    auth_limit = block_end(lines, auth_index)
    auth_child = child_indent(lines, auth_index, auth_limit, 2)
    section_index, section_inline = find_key(
        lines, auth_index + 1, auth_limit, section, indent=auth_child)
    return auth_index, auth_limit, auth_child, section_index, section_inline


def quote(value):
    if re.match(r"^[A-Za-z0-9._/-]+$", value):
        return value
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def parsed_document():
    try:
        import yaml
    except ImportError:
        die("PyYAML is required for the python fallback backend")
    with open(path, "r", encoding="utf-8") as handle:
        document = yaml.safe_load(handle)
    if document is None:
        document = {}
    if not isinstance(document, dict):
        die("config root must be a mapping")
    return document


def entries(section):
    document = parsed_document()
    auth = document.get("auth") or {}
    if not isinstance(auth, dict):
        die("`auth` must be a mapping")
    items = auth.get(section) or []
    if not isinstance(items, list):
        die("`auth.%s` must be a sequence" % section)
    return items


if mode == "ids":
    for entry in entries(arguments[0]):
        if isinstance(entry, dict) and entry.get("id") is not None:
            print(entry["id"])
    raise SystemExit(0)

if mode == "driver-vehicles":
    driver_id = arguments[0]
    for entry in entries("drivers"):
        if not isinstance(entry, dict) or entry.get("id") != driver_id:
            continue
        for vehicle in entry.get("vehicles") or []:
            print(vehicle)
    raise SystemExit(0)

if mode == "add-vehicle":
    vehicle_id, token_path = arguments[0], arguments[1]
    lines, trailing_newline = load_text()
    auth_index, auth_limit, auth_child, index, inline = auth_section(lines, "vehicles")

    if index < 0:
        item = auth_child + 2
        insert_at = block_end(lines, auth_index)
        payload = [
            " " * auth_child + "vehicles:",
            " " * item + "- id: " + quote(vehicle_id),
            " " * (item + 2) + "device_token_file: " + quote(token_path),
        ]
    else:
        if inline and inline != "[]":
            die("`auth.vehicles` uses an inline sequence; install mikefarah/yq v4 to edit it")
        if inline == "[]":
            lines[index] = " " * auth_child + "vehicles:"
            item = auth_child + 2
            insert_at = index + 1
        else:
            limit = block_end(lines, index, auth_limit)
            item = sequence_indent(lines, index + 1, limit, auth_child + 2)
            insert_at = limit
        payload = [
            " " * item + "- id: " + quote(vehicle_id),
            " " * (item + 2) + "device_token_file: " + quote(token_path),
        ]

    lines[insert_at:insert_at] = payload
    store_text(lines, trailing_newline)
    raise SystemExit(0)

if mode == "assign":
    driver_id, vehicle_id = arguments[0], arguments[1]
    lines, trailing_newline = load_text()
    _, _, auth_child, drivers_index, drivers_inline = auth_section(lines, "drivers")
    if drivers_index < 0:
        die("`auth.drivers` not found, cannot assign the vehicle")
    if drivers_inline:
        die("`auth.drivers` uses an inline sequence; install mikefarah/yq v4 to edit it")

    drivers_limit = block_end(lines, drivers_index, None)
    item = sequence_indent(lines, drivers_index + 1, drivers_limit, auth_child + 2)

    starts = [index for index in range(drivers_index + 1, drivers_limit)
              if indent_of(lines[index]) == item and lines[index].lstrip().startswith("- ")]
    span = None
    for position, start in enumerate(starts):
        stop = starts[position + 1] if position + 1 < len(starts) else drivers_limit
        head = re.match(r"^ *- +id: *(.*)$", lines[start])
        matched = head is not None and head.group(1).strip().strip("\"'") == driver_id
        if not matched:
            body, _ = find_key(lines, start + 1, stop, "id", indent=item + 2)
            if body >= 0:
                matched = lines[body].split(":", 1)[1].strip().strip("\"'") == driver_id
        if matched:
            span = (start, stop)
            break
    if span is None:
        die("driver `%s` not found under auth.drivers" % driver_id)

    start, stop = span
    key_index, inline = find_key(lines, start, stop, "vehicles", indent=item + 2)
    if key_index < 0:
        insert_at = block_end(lines, start, stop)
        payload = [
            " " * (item + 2) + "vehicles:",
            " " * (item + 4) + "- " + quote(vehicle_id),
        ]
    elif inline:
        if not (inline.startswith("[") and inline.endswith("]")):
            die("driver `%s` has an unsupported `vehicles` value" % driver_id)
        existing = inline[1:-1].strip()
        merged = "[%s]" % (quote(vehicle_id) if not existing
                           else "%s, %s" % (existing, quote(vehicle_id)))
        lines[key_index] = " " * (item + 2) + "vehicles: " + merged
        store_text(lines, trailing_newline)
        raise SystemExit(0)
    else:
        limit = block_end(lines, key_index, stop)
        entry_indent = sequence_indent(lines, key_index + 1, limit, item + 4)
        insert_at = limit
        payload = [" " * entry_indent + "- " + quote(vehicle_id)]

    lines[insert_at:insert_at] = payload
    store_text(lines, trailing_newline)
    raise SystemExit(0)

die("unknown mode: %s" % mode)
PYTHON
}

yaml_ids() {
  local file="$1" section="$2"
  case "$yaml_engine" in
    yq)
      # Literal paths rather than a dynamic key: `.auth[strenv(...)]` support
      # varies across yq v4 releases.
      if [[ "$section" == "vehicles" ]]; then
        yq eval '(.auth.vehicles // [])[].id // ""' -- "$file"
      else
        yq eval '(.auth.drivers // [])[].id // ""' -- "$file"
      fi
      ;;
    python) python_yaml ids "$file" "$section" ;;
  esac
}

yaml_driver_vehicles() {
  local file="$1" driver="$2"
  case "$yaml_engine" in
    yq)
      DRIVER="$driver" yq eval \
        '(.auth.drivers // [])[] | select(.id == strenv(DRIVER)) | (.vehicles // [])[]' -- "$file"
      ;;
    python) python_yaml driver-vehicles "$file" "$driver" ;;
  esac
}

yaml_add_vehicle() {
  local file="$1" vehicle="$2" token="$3"
  case "$yaml_engine" in
    yq)
      VEHICLE="$vehicle" TOKEN="$token" yq eval -i \
        '.auth.vehicles += [{"id": strenv(VEHICLE), "device_token_file": strenv(TOKEN)}]' -- "$file"
      ;;
    python) python_yaml add-vehicle "$file" "$vehicle" "$token" ;;
  esac
}

yaml_assign_vehicle() {
  local file="$1" driver="$2" vehicle="$3"
  case "$yaml_engine" in
    yq)
      DRIVER="$driver" VEHICLE="$vehicle" yq eval -i \
        '(.auth.drivers[] | select(.id == strenv(DRIVER)) | .vehicles) += [strenv(VEHICLE)]' -- "$file"
      ;;
    python) python_yaml assign "$file" "$driver" "$vehicle" ;;
  esac
}

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

vehicle_id=""
config_path=""
secrets_dir=""
dry_run="no"
force="no"
drivers=()

while (($#)); do
  case "$1" in
    --id)
      [[ $# -ge 2 ]] || fail "--id requires a value"
      vehicle_id="$2"
      shift 2
      ;;
    --config)
      [[ $# -ge 2 ]] || fail "--config requires a value"
      config_path="$2"
      shift 2
      ;;
    --secrets-dir)
      [[ $# -ge 2 ]] || fail "--secrets-dir requires a value"
      secrets_dir="$2"
      shift 2
      ;;
    --assign-to-driver)
      [[ $# -ge 2 ]] || fail "--assign-to-driver requires a value"
      drivers+=("$2")
      shift 2
      ;;
    --force)
      force="yes"
      shift
      ;;
    --dry-run)
      dry_run="yes"
      shift
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *)
      printf 'unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ -n "$vehicle_id" ]] || { printf 'missing --id\n' >&2; usage >&2; exit 2; }
[[ -n "$config_path" ]] || { printf 'missing --config\n' >&2; usage >&2; exit 2; }
[[ "$vehicle_id" =~ ^[A-Za-z0-9._-]+$ ]] ||
  fail "vehicle id may only contain letters, digits, dot, underscore and dash: $vehicle_id"
[[ -f "$config_path" && -r "$config_path" ]] || fail "config is not a readable file: $config_path"
[[ -w "$config_path" ]] || fail "config is not writable: $config_path"

for driver in ${drivers[@]+"${drivers[@]}"}; do
  [[ "$driver" =~ ^[A-Za-z0-9._-]+$ ]] ||
    fail "driver id may only contain letters, digits, dot, underscore and dash: $driver"
done

# De-duplicate repeated --assign-to-driver values while keeping the given order.
unique_drivers=()
for driver in ${drivers[@]+"${drivers[@]}"}; do
  known="no"
  for seen in ${unique_drivers[@]+"${unique_drivers[@]}"}; do
    if [[ "$seen" == "$driver" ]]; then known="yes"; break; fi
  done
  [[ "$known" == "yes" ]] || unique_drivers+=("$driver")
done
drivers=(${unique_drivers[@]+"${unique_drivers[@]}"})

command -v openssl >/dev/null 2>&1 || fail "openssl is required to generate the device token"
select_yaml_engine

config_path="$(CDPATH= cd -- "$(dirname -- "$config_path")" && pwd)/$(basename -- "$config_path")"
config_dir="$(dirname -- "$config_path")"
[[ -n "$secrets_dir" ]] || secrets_dir="$config_dir/secrets"
token_path="${secrets_dir%/}/${vehicle_id}.token"

# `device_token_file` is resolved relative to the config directory by the server,
# so prefer a relative reference. The plain prefix strip keeps the common case
# working without GNU realpath (BSD/macOS lacks --relative-to).
case "$token_path" in
  "$config_dir"/*)
    token_reference="${token_path#"$config_dir"/}"
    ;;
  *)
    token_reference="$(realpath --relative-to="$config_dir" -m -- "$token_path" 2>/dev/null || true)"
    if [[ -z "$token_reference" || "$token_reference" == ..* ]]; then
      token_reference="$(realpath -m -- "$token_path" 2>/dev/null || printf '%s' "$token_path")"
    fi
    ;;
esac

# ---------------------------------------------------------------------------
# Validation against the current config
# ---------------------------------------------------------------------------

step "inspecting $config_path"
# Read in the parent shell: a backend failure must abort here, because an
# unreadable section would otherwise look like an empty one and defeat the
# duplicate checks below.
vehicles_raw="$(yaml_ids "$config_path" vehicles)" ||
  fail "cannot read auth.vehicles from $config_path (is it valid YAML?)"
drivers_raw="$(yaml_ids "$config_path" drivers)" ||
  fail "cannot read auth.drivers from $config_path (is it valid YAML?)"

existing_vehicles=()
while IFS= read -r line; do
  if [[ -n "$line" ]]; then existing_vehicles+=("$line"); fi
done <<<"$vehicles_raw"
existing_drivers=()
while IFS= read -r line; do
  if [[ -n "$line" ]]; then existing_drivers+=("$line"); fi
done <<<"$drivers_raw"

for existing in ${existing_vehicles[@]+"${existing_vehicles[@]}"}; do
  if [[ "$existing" == "$vehicle_id" ]]; then
    fail "vehicle id already present in $config_path: $vehicle_id (the server rejects duplicates)"
  fi
done
note "vehicles configured: ${#existing_vehicles[@]}, drivers configured: ${#existing_drivers[@]}"

assign_drivers=()
for driver in ${drivers[@]+"${drivers[@]}"}; do
  known="no"
  for existing in ${existing_drivers[@]+"${existing_drivers[@]}"}; do
    if [[ "$existing" == "$driver" ]]; then known="yes"; break; fi
  done
  [[ "$known" == "yes" ]] || fail "driver not found in $config_path: $driver"
  permitted_raw="$(yaml_driver_vehicles "$config_path" "$driver")" ||
    fail "cannot read the vehicle permissions of $driver from $config_path"
  already="no"
  while IFS= read -r permitted; do
    if [[ "$permitted" == "$vehicle_id" ]]; then already="yes"; fi
  done <<<"$permitted_raw"
  if [[ "$already" == "yes" ]]; then
    warn "$driver already lists $vehicle_id; leaving its permissions untouched"
  else
    assign_drivers+=("$driver")
  fi
done

if [[ -e "$token_path" && "$force" != "yes" ]]; then
  fail "token file already exists: $token_path (pass --force to regenerate it)"
fi

# ---------------------------------------------------------------------------
# Config validator discovery
# ---------------------------------------------------------------------------

find_validator() {
  local candidate
  if [[ -n "${MINE_TELEOP_SIGNALING_BIN:-}" ]]; then
    printf '%s' "$MINE_TELEOP_SIGNALING_BIN"
    return 0
  fi
  if candidate="$(command -v mine-teleop-signaling-server 2>/dev/null)"; then
    printf '%s' "$candidate"
    return 0
  fi
  for candidate in \
    "${MINE_TELEOP_BUILD_DIR:-$repo_root/build}/mine-teleop-signaling-server" \
    "$repo_root"/build/*/mine-teleop-signaling-server; do
    [[ -x "$candidate" ]] || continue
    printf '%s' "$candidate"
    return 0
  done
  return 1
}

validate_config() {
  local file="$1"
  env -u MINE_TELEOP_DRIVER_PASSWORD -u MINE_TELEOP_DEVICE_TOKEN \
    -u MINE_TELEOP_SIGNALING_CONFIG \
    "$validator" --validate-config --config "$file" 2>&1
}

validator=""
baseline_valid="unknown"
# Checked here rather than inside find_validator: that runs in a command
# substitution, where an abort would only end the subshell.
if [[ -n "${MINE_TELEOP_SIGNALING_BIN:-}" && ! -x "${MINE_TELEOP_SIGNALING_BIN}" ]]; then
  fail "MINE_TELEOP_SIGNALING_BIN is not executable: $MINE_TELEOP_SIGNALING_BIN"
fi
if validator="$(find_validator)"; then
  note "validator: $validator"
  if validate_config "$config_path" >/dev/null 2>&1; then
    baseline_valid="yes"
  else
    baseline_valid="no"
    warn "the unmodified config does not validate in this environment; post-change validation will be skipped"
  fi
else
  note "validator: not found (skipping --validate-config)"
fi

# ---------------------------------------------------------------------------
# Dry run
# ---------------------------------------------------------------------------

if [[ "$dry_run" == "yes" ]]; then
  step "dry run: no files are written"
  note "token file            $token_path (mode 0600, 32 random bytes hex)"
  note "secrets directory     $secrets_dir$([[ -d "$secrets_dir" ]] || printf ' (would be created, mode 0700)')"
  note "yaml                  $config_path"
  note "backend               $yaml_engine"
  printf '\n%sauth.vehicles gains:%s\n' "$color_bold" "$color_reset"
  printf '  - id: %s\n    device_token_file: %s\n' "$vehicle_id" "$token_reference"
  if ((${#assign_drivers[@]})); then
    printf '\n%sauth.drivers permissions gain %s:%s\n' "$color_bold" "$vehicle_id" "$color_reset"
    for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
      printf '  %s\n' "$driver"
    done
  fi
  printf '\n'
  ok "dry run finished; rerun without --dry-run to apply"
  exit 0
fi

# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

created_token="no"
temporary_config=""
committed="no"

cleanup() {
  [[ -z "$temporary_config" ]] || rm -f -- "$temporary_config"
  if [[ "$committed" != "yes" && "$created_token" == "yes" ]]; then
    rm -f -- "$token_path"
    warn "removed the freshly generated token $token_path because the config was not updated"
  fi
}
trap cleanup EXIT

step "generating device token"
if [[ ! -d "$secrets_dir" ]]; then
  mkdir -p -- "$secrets_dir"
  chmod 0700 -- "$secrets_dir"
  note "created $secrets_dir (mode 0700)"
fi
[[ -d "$secrets_dir" && -w "$secrets_dir" ]] || fail "secrets directory is not writable: $secrets_dir"

(
  umask 077
  openssl rand -hex 32 >"$token_path"
)
created_token="yes"
chmod 0600 -- "$token_path"
[[ -n "$(tr -d '[:space:]' <"$token_path")" ]] || fail "generated token file is empty: $token_path"
ok "wrote $token_path (mode 0600)"

step "updating $config_path"
config_mode="$(stat -c '%a' -- "$config_path" 2>/dev/null || stat -f '%Lp' -- "$config_path")"
temporary_config="$(mktemp "$config_dir/.add_vehicle.$(basename -- "$config_path").XXXXXX")"
cat -- "$config_path" >"$temporary_config"

yaml_add_vehicle "$temporary_config" "$vehicle_id" "$token_reference"
note "auth.vehicles += $vehicle_id"
for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
  yaml_assign_vehicle "$temporary_config" "$driver" "$vehicle_id"
  note "auth.drivers[$driver].vehicles += $vehicle_id"
done

if [[ "$baseline_valid" == "yes" ]]; then
  step "validating the updated config"
  if ! validation_output="$(validate_config "$temporary_config")"; then
    printf '%s\n' "$validation_output" >&2
    fail "the updated config was rejected; $config_path is unchanged"
  fi
  ok "mine-teleop-signaling-server --validate-config accepted the config"
fi

chmod "$config_mode" -- "$temporary_config"
mv -f -- "$temporary_config" "$config_path"
temporary_config=""
committed="yes"
ok "updated $config_path"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

printf '\n%ssummary%s\n' "$color_bold" "$color_reset"
printf '  vehicle id       %s\n' "$vehicle_id"
printf '  token file       %s\n' "$token_path"
printf '  token reference  device_token_file: %s\n' "$token_reference"
printf '  config           %s\n' "$config_path"
if ((${#assign_drivers[@]})); then
  printf '  drivers updated  %s\n' "${assign_drivers[*]}"
else
  printf '  drivers updated  none (no driver may reach %s yet)\n' "$vehicle_id"
fi
case "$baseline_valid" in
  yes) printf '  validation       passed\n' ;;
  no) printf '  validation       skipped (the config already failed validation before the change)\n' ;;
  *) printf '  validation       skipped (mine-teleop-signaling-server not found)\n' ;;
esac
printf '\n%sReminder:%s restart the signaling server to load the new identity, e.g.\n' \
  "$color_yellow" "$color_reset"
printf '  sudo systemctl restart mine-teleop-signaling-server.service\n'
printf 'Then provision %s on the vehicle: copy the token to its host and point\n' "$vehicle_id"
printf 'cloud.device_token_file at it in the vehicle agent config.\n'
