#!/usr/bin/env bash
#
# add_vehicle.sh - register a new vehicle identity in a signaling server config.
#
# Usage:
#   add_vehicle.sh --id VEHICLE_ID --config YAML_PATH
#                  [--secrets-dir DIR] [--assign-to-driver DRIVER_ID]...
#                  [--force] [--dry-run] [--help]
#
# The script generates a 32-byte hex device token, stores it with mode 0600, adds
#
#   auth:
#     vehicles:
#       - id: <vehicle-id>
#         device_token_file: secrets/<vehicle-id>.token
#
# to the signaling server YAML, and optionally appends the vehicle to the
# `vehicles` permission list of one or more drivers under `auth.drivers`.
#
# Guarantees:
#   * vehicle ids are rejected when they already exist (the server refuses to
#     start on duplicates);
#   * `device_token_file` is written relative to the YAML directory, which is how
#     the server resolves relative secret paths;
#   * the YAML is edited on a sibling temporary copy and only moved into place
#     after `mine-teleop-signaling-server --validate-config` accepts it (skipped
#     when the binary is unavailable, or when the untouched config already fails
#     validation in this environment, e.g. because `password_env` secrets are not
#     exported);
#   * a token generated by a run that later fails is removed again.
#
# YAML editing backend: `yq` (https://github.com/mikefarah/yq, v4) when present,
# otherwise a python3 + PyYAML fallback that inserts lines in place. Both keep
# surrounding comments and formatting intact.
#
# Environment:
#   MINE_TELEOP_SIGNALING_BIN  explicit path to mine-teleop-signaling-server
#   MINE_TELEOP_BUILD_DIR      build directory searched for the server binary
#   NO_COLOR                   disable colored output
#
set -euo pipefail

script_dir="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(CDPATH= cd -- "$script_dir/../.." && pwd)"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  color_red=$'\033[31m'
  color_green=$'\033[32m'
  color_yellow=$'\033[33m'
  color_blue=$'\033[34m'
  color_bold=$'\033[1m'
  color_reset=$'\033[0m'
else
  color_red="" color_green="" color_yellow="" color_blue="" color_bold="" color_reset=""
fi

step() { printf '%s==>%s %s\n' "$color_blue" "$color_reset" "$*"; }
note() { printf '    %s\n' "$*"; }
ok() { printf '%s ok %s %s\n' "$color_green" "$color_reset" "$*"; }
warn() { printf '%swarn%s %s\n' "$color_yellow" "$color_reset" "$*" >&2; }
fail() { printf '%sfail%s %s\n' "$color_red" "$color_reset" "$*" >&2; exit 2; }

usage() {
  cat <<'EOF'
Usage:
  add_vehicle.sh --id VEHICLE_ID --config YAML_PATH [options]

Required:
  --id VEHICLE_ID              vehicle identity to register, e.g. vehicle-003
  --config YAML_PATH           signaling server multi-identity YAML

Options:
  --secrets-dir DIR            token directory (default: .local for repo configs,
                               otherwise <yaml dir>/secrets)
  --assign-to-driver DRIVER_ID append the vehicle to this driver's permission
                               list; may be repeated
  --force                      overwrite an existing token file
  --dry-run                    report the planned changes without writing
  --help                       show this help

Examples:
  add_vehicle.sh --id vehicle-003 --config /etc/mine-teleop/signaling-server.yaml
  add_vehicle.sh --id vehicle-003 --config configs/signaling-server.2x2.dev.yaml \
      --assign-to-driver driver-console-001 --dry-run
EOF
}

# ---------------------------------------------------------------------------
# YAML backend
# ---------------------------------------------------------------------------

# Keep this user-facing entrypoint and its credential transaction local; the
# shared library owns only engine dispatch and YAML edits.
# shellcheck source=lib/yaml_editor.sh
source "$script_dir/lib/yaml_editor.sh"

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

vehicle_id=""
config_path=""
secrets_dir=""
dry_run="no"
force="no"
drivers=()

while (($#)); do
  case "$1" in
    --id)
      [[ $# -ge 2 ]] || fail "--id requires a value"
      vehicle_id="$2"
      shift 2
      ;;
    --config)
      [[ $# -ge 2 ]] || fail "--config requires a value"
      config_path="$2"
      shift 2
      ;;
    --secrets-dir)
      [[ $# -ge 2 ]] || fail "--secrets-dir requires a value"
      secrets_dir="$2"
      shift 2
      ;;
    --assign-to-driver)
      [[ $# -ge 2 ]] || fail "--assign-to-driver requires a value"
      drivers+=("$2")
      shift 2
      ;;
    --force)
      force="yes"
      shift
      ;;
    --dry-run)
      dry_run="yes"
      shift
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *)
      printf 'unknown option: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

[[ -n "$vehicle_id" ]] || { printf 'missing --id\n' >&2; usage >&2; exit 2; }
[[ -n "$config_path" ]] || { printf 'missing --config\n' >&2; usage >&2; exit 2; }
[[ "$vehicle_id" =~ ^[A-Za-z0-9._-]+$ ]] ||
  fail "vehicle id may only contain letters, digits, dot, underscore and dash: $vehicle_id"
[[ -f "$config_path" && -r "$config_path" ]] || fail "config is not a readable file: $config_path"
[[ -w "$config_path" ]] || fail "config is not writable: $config_path"

for driver in ${drivers[@]+"${drivers[@]}"}; do
  [[ "$driver" =~ ^[A-Za-z0-9._-]+$ ]] ||
    fail "driver id may only contain letters, digits, dot, underscore and dash: $driver"
done

# De-duplicate repeated --assign-to-driver values while keeping the given order.
unique_drivers=()
for driver in ${drivers[@]+"${drivers[@]}"}; do
  known="no"
  for seen in ${unique_drivers[@]+"${unique_drivers[@]}"}; do
    if [[ "$seen" == "$driver" ]]; then known="yes"; break; fi
  done
  [[ "$known" == "yes" ]] || unique_drivers+=("$driver")
done
drivers=(${unique_drivers[@]+"${unique_drivers[@]}"})

command -v openssl >/dev/null 2>&1 || fail "openssl is required to generate the device token"
select_yaml_engine

config_path="$(CDPATH= cd -- "$(dirname -- "$config_path")" && pwd)/$(basename -- "$config_path")"
config_dir="$(dirname -- "$config_path")"
# Keep credentials generated for repository development configs out of the
# distributable configs tree. Installed /etc-style configs continue to use a
# sibling secrets directory. An explicit --secrets-dir is resolved against the
# caller's CWD (matching add_driver.sh).
if [[ -z "$secrets_dir" ]]; then
  if [[ "$config_dir" == "$repo_root/configs" ]]; then
    secrets_dir="$repo_root/.local/secrets/$(basename -- "$config_path" .yaml)"
  else
    secrets_dir="$config_dir/secrets"
  fi
elif [[ "$secrets_dir" != /* ]]; then
  secrets_dir="$PWD/$secrets_dir"
fi
secrets_dir="${secrets_dir%/}"
token_path="$secrets_dir/${vehicle_id}.token"

# `device_token_file` is resolved relative to the config directory by the server.
# The repository's `configs/` and `.local/` directories are siblings, but that
# relationship must not be assumed for an arbitrary YAML supplied by the caller.
token_reference="$token_path"
if [[ "$config_dir" == "$repo_root/configs" && "$token_path" == "$repo_root/.local/"* ]]; then
  token_reference="../${token_path#"$repo_root"/}"
elif [[ "$token_path" == "$config_dir/"* ]]; then
  token_reference="${token_path#"$config_dir"/}"
else
  relative="$(realpath --relative-to="$config_dir" -m -- "$token_path" 2>/dev/null || true)"
  if [[ -n "$relative" && "$relative" != /* && "$relative" != ../* ]]; then
    token_reference="$relative"
  else
    token_reference="$(realpath -m -- "$token_path" 2>/dev/null || printf '%s' "$token_path")"
  fi
fi

# ---------------------------------------------------------------------------
# Validation against the current config
# ---------------------------------------------------------------------------

step "inspecting $config_path"
# Read in the parent shell: a backend failure must abort here, because an
# unreadable section would otherwise look like an empty one and defeat the
# duplicate checks below.
vehicles_raw="$(yaml_ids "$config_path" vehicles)" ||
  fail "cannot read auth.vehicles from $config_path (is it valid YAML?)"
drivers_raw="$(yaml_ids "$config_path" drivers)" ||
  fail "cannot read auth.drivers from $config_path (is it valid YAML?)"

existing_vehicles=()
while IFS= read -r line; do
  if [[ -n "$line" ]]; then existing_vehicles+=("$line"); fi
done <<<"$vehicles_raw"
existing_drivers=()
while IFS= read -r line; do
  if [[ -n "$line" ]]; then existing_drivers+=("$line"); fi
done <<<"$drivers_raw"

for existing in ${existing_vehicles[@]+"${existing_vehicles[@]}"}; do
  if [[ "$existing" == "$vehicle_id" ]]; then
    fail "vehicle id already present in $config_path: $vehicle_id (the server rejects duplicates)"
  fi
done
note "vehicles configured: ${#existing_vehicles[@]}, drivers configured: ${#existing_drivers[@]}"

assign_drivers=()
for driver in ${drivers[@]+"${drivers[@]}"}; do
  known="no"
  for existing in ${existing_drivers[@]+"${existing_drivers[@]}"}; do
    if [[ "$existing" == "$driver" ]]; then known="yes"; break; fi
  done
  [[ "$known" == "yes" ]] || fail "driver not found in $config_path: $driver"
  permitted_raw="$(yaml_driver_vehicles "$config_path" "$driver")" ||
    fail "cannot read the vehicle permissions of $driver from $config_path"
  already="no"
  while IFS= read -r permitted; do
    if [[ "$permitted" == "$vehicle_id" ]]; then already="yes"; fi
  done <<<"$permitted_raw"
  if [[ "$already" == "yes" ]]; then
    warn "$driver already lists $vehicle_id; leaving its permissions untouched"
  else
    assign_drivers+=("$driver")
  fi
done

if [[ -e "$token_path" && "$force" != "yes" ]]; then
  fail "token file already exists: $token_path (pass --force to regenerate it)"
fi

# ---------------------------------------------------------------------------
# Config validator discovery
# ---------------------------------------------------------------------------

find_validator() {
  local candidate
  if [[ -n "${MINE_TELEOP_SIGNALING_BIN:-}" ]]; then
    printf '%s' "$MINE_TELEOP_SIGNALING_BIN"
    return 0
  fi
  if candidate="$(command -v mine-teleop-signaling-server 2>/dev/null)"; then
    printf '%s' "$candidate"
    return 0
  fi
  for candidate in \
    "${MINE_TELEOP_BUILD_DIR:-$repo_root/build}/mine-teleop-signaling-server" \
    "$repo_root"/build/*/mine-teleop-signaling-server; do
    [[ -x "$candidate" ]] || continue
    printf '%s' "$candidate"
    return 0
  done
  return 1
}

# Validate a rendered config. Returns 0 when the server accepts it, or when the
# only failure is a pre-existing identity whose secret comes from the
# environment (unrelated to the file-based vehicle added here). Any other
# failure is propagated. The outcome is recorded in validation_note.
validation_note=""
validate_config() {
  local file="$1" output status=0
  output="$(env -u MINE_TELEOP_DRIVER_PASSWORD -u MINE_TELEOP_DEVICE_TOKEN \
    -u MINE_TELEOP_SIGNALING_CONFIG \
    "$validator" --validate-config --config "$file" 2>&1)" || status=$?
  if [[ $status -eq 0 ]]; then
    validation_note="passed"
    return 0
  fi
  if grep -q 'environment variable is unset or empty' <<<"$output"; then
    warn "skipped full validation: an existing identity reads its secret from the environment"
    validation_note="skipped (an existing identity reads its secret from the environment)"
    return 0
  fi
  printf '%s\n' "$output" >&2
  return "$status"
}

validator=""
# Checked here rather than inside find_validator: that runs in a command
# substitution, where an abort would only end the subshell.
if [[ -n "${MINE_TELEOP_SIGNALING_BIN:-}" && ! -x "${MINE_TELEOP_SIGNALING_BIN}" ]]; then
  fail "MINE_TELEOP_SIGNALING_BIN is not executable: $MINE_TELEOP_SIGNALING_BIN"
fi
if validator="$(find_validator)"; then
  note "validator: $validator"
else
  validator=""
  note "validator: not found (skipping --validate-config)"
fi

# ---------------------------------------------------------------------------
# Dry run
# ---------------------------------------------------------------------------

if [[ "$dry_run" == "yes" ]]; then
  step "dry run: no files are written"
  note "token file            $token_path (mode 0600, 32 random bytes hex)"
  note "secrets directory     $secrets_dir$([[ -d "$secrets_dir" ]] || printf ' (would be created, mode 0700)')"
  note "yaml                  $config_path"
  note "backend               $yaml_engine"
  printf '\n%sauth.vehicles gains:%s\n' "$color_bold" "$color_reset"
  printf '  - id: %s\n    device_token_file: %s\n' "$vehicle_id" "$token_reference"
  if ((${#assign_drivers[@]})); then
    printf '\n%sauth.drivers permissions gain %s:%s\n' "$color_bold" "$vehicle_id" "$color_reset"
    for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
      printf '  %s\n' "$driver"
    done
  fi
  printf '\n'
  ok "dry run finished; rerun without --dry-run to apply"
  exit 0
fi

# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

created_token="no"
created_secrets_dir="no"
temporary_config=""
temporary_token=""
token_backup=""
committed="no"

cleanup() {
  [[ -z "$temporary_config" ]] || rm -f -- "$temporary_config"
  [[ -z "$temporary_token" ]] || rm -f -- "$temporary_token"
  if [[ "$committed" != "yes" && "$created_token" == "yes" ]]; then
    if [[ -n "$token_backup" && -f "$token_backup" ]]; then
      mv -f -- "$token_backup" "$token_path"
      token_backup=""
      warn "restored the previous token because the config was not updated"
    else
      rm -f -- "$token_path"
      warn "removed the freshly generated token $token_path because the config was not updated"
    fi
  fi
  [[ -z "$token_backup" ]] || rm -f -- "$token_backup"
  if [[ "$committed" != "yes" && "$created_secrets_dir" == "yes" ]]; then
    rmdir -- "$secrets_dir" 2>/dev/null || true
  fi
  return 0
}
trap cleanup EXIT

step "generating device token"
if [[ ! -d "$secrets_dir" ]]; then
  mkdir -p -- "$secrets_dir"
  created_secrets_dir="yes"
  chmod 0700 "$secrets_dir"
  note "created $secrets_dir (mode 0700)"
fi
[[ -d "$secrets_dir" && -w "$secrets_dir" ]] || fail "secrets directory is not writable: $secrets_dir"

temporary_token="$(mktemp "$secrets_dir/.${vehicle_id}.token.XXXXXX")"
if ! (
  umask 077
  openssl rand -hex 32 >"$temporary_token"
); then
  rm -f -- "$temporary_token"
  temporary_token=""
  fail "openssl failed to generate a device token for $vehicle_id"
fi
chmod 0600 "$temporary_token"
[[ -n "$(tr -d '[:space:]' <"$temporary_token")" ]] || fail "generated token file is empty"
if [[ -e "$token_path" ]]; then
  backup_candidate="$(mktemp "$secrets_dir/.${vehicle_id}.token.backup.XXXXXX")"
  if ! cp -p "$token_path" "$backup_candidate"; then
    rm -f -- "$backup_candidate"
    fail "cannot back up the existing token: $token_path"
  fi
  chmod 0600 "$backup_candidate"
  token_backup="$backup_candidate"
fi
created_token="yes"
mv -f -- "$temporary_token" "$token_path"
temporary_token=""
ok "wrote $token_path (mode 0600)"

step "updating $config_path"
config_mode="$(stat -c '%a' -- "$config_path" 2>/dev/null || stat -f '%Lp' -- "$config_path")"
temporary_config="$(mktemp "$config_dir/.add_vehicle.$(basename -- "$config_path").XXXXXX")"
cat -- "$config_path" >"$temporary_config"

yaml_add_vehicle "$temporary_config" "$vehicle_id" "$token_reference"
note "auth.vehicles += $vehicle_id"
for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
  yaml_assign_vehicle "$temporary_config" "$driver" "$vehicle_id"
  note "auth.drivers[$driver].vehicles += $vehicle_id"
done

# Re-read the rendered config: the text backend edits by indentation, so confirm
# the change landed exactly once before trusting it (validation may be partial).
step "verifying the pending config"
if [[ "$(yaml_ids "$temporary_config" vehicles | grep -c -x -F -- "$vehicle_id")" != "1" ]]; then
  fail "the rendered config does not contain exactly one '$vehicle_id' vehicle; $config_path is unchanged"
fi
for driver in ${assign_drivers[@]+"${assign_drivers[@]}"}; do
  if ! yaml_driver_vehicles "$temporary_config" "$driver" | grep -q -x -F -- "$vehicle_id"; then
    fail "driver $driver did not gain $vehicle_id in the rendered config; $config_path is unchanged"
  fi
done

if [[ -n "$validator" ]]; then
  step "validating the updated config"
  if ! validate_config "$temporary_config"; then
    fail "the updated config was rejected; $config_path is unchanged"
  fi
  if [[ "$validation_note" == "passed" ]]; then
    ok "mine-teleop-signaling-server --validate-config accepted the config"
  fi
fi

chmod "$config_mode" "$temporary_config"
mv -f -- "$temporary_config" "$config_path"
temporary_config=""
committed="yes"
[[ -z "$token_backup" ]] || rm -f -- "$token_backup"
token_backup=""
ok "updated $config_path"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

printf '\n%ssummary%s\n' "$color_bold" "$color_reset"
printf '  vehicle id       %s\n' "$vehicle_id"
printf '  token file       %s\n' "$token_path"
printf '  token reference  device_token_file: %s\n' "$token_reference"
printf '  config           %s\n' "$config_path"
if ((${#assign_drivers[@]})); then
  printf '  drivers updated  %s\n' "${assign_drivers[*]}"
else
  printf '  drivers updated  none (no driver may reach %s yet)\n' "$vehicle_id"
fi
if [[ -z "$validator" ]]; then
  printf '  validation       skipped (mine-teleop-signaling-server not found)\n'
elif [[ "$validation_note" == "passed" ]]; then
  printf '  validation       passed\n'
else
  printf '  validation       %s\n' "$validation_note"
fi
printf '\n%sReminder:%s restart the signaling server to load the new identity, e.g.\n' \
  "$color_yellow" "$color_reset"
printf '  sudo systemctl restart mine-teleop-signaling-server.service\n'
printf 'Then provision %s on the vehicle: copy the token to its host and point\n' "$vehicle_id"
printf 'cloud.device_token_file at it in the vehicle agent config.\n'
