#!/usr/bin/env bash
set -euo pipefail

# Edit this block once, then run this script on the vehicle:
#   scripts/start_live_vehicle_one_command.sh
INSTALL_DIR="/home/user/mine-teleop"
SIGNALING_HTTP_URL="http://127.0.0.1:8765"
DEVICE_TOKEN="replace-with-device-token"
CAMERA_DEVICES="front=/dev/video0 rear=/dev/video2"
MVS_CAMERAS="hikrobot=mvs:0"
PYLON_CAMERAS="basler=pylon:0"
REALTIME_PROFILE="realtime_480p15"
CAPTURE_WIDTH="640"
CAPTURE_HEIGHT="480"
CAPTURE_FPS="15"
MVS_CAPTURE_WIDTH="640"
MVS_CAPTURE_HEIGHT="512"
MVS_CAPTURE_FPS="15"
MVS_JPEG_QUALITY="65"
PYLON_CAPTURE_WIDTH="640"
PYLON_CAPTURE_HEIGHT="512"
PYLON_CAPTURE_FPS="15"
CAMERA_CONTROL_PROFILE="adaptive"
CAMERA_AUTO_EXPOSURE="3"
CAMERA_GAIN_AUTOMATIC="1"
CAMERA_WHITE_BALANCE_AUTO="1"
CAMERA_ADAPTIVE_BRIGHTNESS="0"
CAMERA_ADAPTIVE_CONTRAST="32"
CAMERA_ADAPTIVE_GAMMA="300"
CAMERA_ADAPTIVE_BACKLIGHT="1"
CAMERA_POWER_LINE_FREQUENCY="1"
STOP_EXISTING_MEDIA="1"

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

stop_existing_media() {
  local pids
  pids="$(
    ps -eo pid,args | awk -v install_dir="$INSTALL_DIR" '
      ($2=="bash" && ($3=="scripts/run_vehicle_live_media.sh" || $3==install_dir "/scripts/run_vehicle_live_media.sh")) ||
      ($2==install_dir "/lib/ld-linux-x86-64.so.2" && $0 ~ /bin\/mine-teleop/ &&
        ($0 ~ /vehicle-media-agent/ || $0 ~ /mvs-camera-bridge/)) ||
      ($2==install_dir "/bin/pylon-camera-bridge") {
        print $1
      }
    '
  )"
  if [[ -n "$pids" ]]; then
    # shellcheck disable=SC2086
    kill -TERM $pids 2>/dev/null || true
    sleep 2
  fi
}

if [[ "$STOP_EXISTING_MEDIA" == "1" ]]; then
  stop_existing_media
fi

cd "$INSTALL_DIR"
exec env \
  MINE_TELEOP_INSTALL_DIR="$INSTALL_DIR" \
  MINE_TELEOP_SIGNALING_HTTP_URL="$SIGNALING_HTTP_URL" \
  MINE_TELEOP_DEVICE_TOKEN="$DEVICE_TOKEN" \
  MINE_TELEOP_CAMERA_DEVICES="$CAMERA_DEVICES" \
  MINE_TELEOP_MVS_CAMERAS="$MVS_CAMERAS" \
  MINE_TELEOP_PYLON_CAMERAS="$PYLON_CAMERAS" \
  MINE_TELEOP_REALTIME_PROFILE="$REALTIME_PROFILE" \
  MINE_TELEOP_CAPTURE_WIDTH="$CAPTURE_WIDTH" \
  MINE_TELEOP_CAPTURE_HEIGHT="$CAPTURE_HEIGHT" \
  MINE_TELEOP_CAPTURE_FPS="$CAPTURE_FPS" \
  MINE_TELEOP_MVS_CAPTURE_WIDTH="$MVS_CAPTURE_WIDTH" \
  MINE_TELEOP_MVS_CAPTURE_HEIGHT="$MVS_CAPTURE_HEIGHT" \
  MINE_TELEOP_MVS_CAPTURE_FPS="$MVS_CAPTURE_FPS" \
  MINE_TELEOP_MVS_JPEG_QUALITY="$MVS_JPEG_QUALITY" \
  MINE_TELEOP_PYLON_CAPTURE_WIDTH="$PYLON_CAPTURE_WIDTH" \
  MINE_TELEOP_PYLON_CAPTURE_HEIGHT="$PYLON_CAPTURE_HEIGHT" \
  MINE_TELEOP_PYLON_CAPTURE_FPS="$PYLON_CAPTURE_FPS" \
  MINE_TELEOP_CAMERA_CONTROL_PROFILE="$CAMERA_CONTROL_PROFILE" \
  MINE_TELEOP_CAMERA_AUTO_EXPOSURE="$CAMERA_AUTO_EXPOSURE" \
  MINE_TELEOP_CAMERA_GAIN_AUTOMATIC="$CAMERA_GAIN_AUTOMATIC" \
  MINE_TELEOP_CAMERA_WHITE_BALANCE_AUTO="$CAMERA_WHITE_BALANCE_AUTO" \
  MINE_TELEOP_CAMERA_ADAPTIVE_BRIGHTNESS="$CAMERA_ADAPTIVE_BRIGHTNESS" \
  MINE_TELEOP_CAMERA_ADAPTIVE_CONTRAST="$CAMERA_ADAPTIVE_CONTRAST" \
  MINE_TELEOP_CAMERA_ADAPTIVE_GAMMA="$CAMERA_ADAPTIVE_GAMMA" \
  MINE_TELEOP_CAMERA_ADAPTIVE_BACKLIGHT="$CAMERA_ADAPTIVE_BACKLIGHT" \
  MINE_TELEOP_CAMERA_POWER_LINE_FREQUENCY="$CAMERA_POWER_LINE_FREQUENCY" \
  "$SCRIPT_DIR/run_vehicle_live_media.sh"
