#!/usr/bin/env bash
set -euo pipefail

# Edit this block once, then run:
#   scripts/start_live_control_one_command.sh
VEHICLE_SSH_HOST="60.205.213.254"
VEHICLE_SSH_PORT="6000"
VEHICLE_SSH_USER="user"
VEHICLE_SSH_PASSWORD="CHANGE_ME"

DRIVER_CONSOLE_LOCAL_PORT="8888"
SIGNALING_LOCAL_PORT="8876"
DRIVER_CONSOLE_REMOTE_PORT="18080"
SIGNALING_REMOTE_PORT="18765"
CONTROL_PLANE_SERVER="mine-teleop-signaling-local"
CONTROL_PLANE_CONSOLE="mine-teleop-driver-console-local"
OPEN_BROWSER="1"

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)"

if [[ "$VEHICLE_SSH_PASSWORD" == "CHANGE_ME" ]]; then
  cat >&2 <<'EOF'
Edit VEHICLE_SSH_PASSWORD in scripts/start_live_control_one_command.sh first.
Set it to an empty string if this host uses SSH key authentication.
EOF
  exit 2
fi

export MINE_TELEOP_VEHICLE_SSH_HOST="$VEHICLE_SSH_HOST"
export MINE_TELEOP_VEHICLE_SSH_PORT="$VEHICLE_SSH_PORT"
export MINE_TELEOP_VEHICLE_SSH_USER="$VEHICLE_SSH_USER"
export MINE_TELEOP_VEHICLE_SSH_PASSWORD="$VEHICLE_SSH_PASSWORD"
export MINE_TELEOP_DRIVER_CONSOLE_LOCAL_PORT="$DRIVER_CONSOLE_LOCAL_PORT"
export MINE_TELEOP_SIGNALING_LOCAL_PORT="$SIGNALING_LOCAL_PORT"
export MINE_TELEOP_DRIVER_CONSOLE_REMOTE_PORT="$DRIVER_CONSOLE_REMOTE_PORT"
export MINE_TELEOP_SIGNALING_REMOTE_PORT="$SIGNALING_REMOTE_PORT"
export MINE_TELEOP_CONTROL_PLANE_SERVER="$CONTROL_PLANE_SERVER"
export MINE_TELEOP_CONTROL_PLANE_CONSOLE="$CONTROL_PLANE_CONSOLE"
export MINE_TELEOP_OPEN_BROWSER="$OPEN_BROWSER"

cd "$REPO_ROOT"
exec scripts/start_live_control_plane_tunnel.sh
